### ISSUE TITLE
No file in npm, when installed

### ISSUE THREAD

**Issue by GillHoang** [Balastrong/wrand#11]
![image](https://user-images.githubusercontent.com/89916615/186425317-6c32dd43-9ce2-45d4-b6fa-78618b693d4f.png)
![image](https://user-images.githubusercontent.com/89916615/186425392-f101fba3-5545-4e5f-8f4f-73ae92665e01.png)

**Comment by Balastrong** [comment]
Thank you very much for the report, I fixed it in #12 

Please run `npm install wrand@latest` to get the latest version, should be fine now! :)

**Comment by Balastrong** [comment]
Fixed with #12
