### ISSUE TITLE
Prevent duplicates on a single call of pickMany

### ISSUE THREAD

**Issue by Balastrong** [Balastrong/wrand#2]
Add a boolean flag on `pickMany` (or a new function, `pickManyDistinct`) to prevent duplicates to be returned in a single call.

Keep an extra eye on cases where the requested amount is higher than the actual items and no duplicates are wanted.

**Comment by AnoopFranc** [comment]
@Balastrong I stumbled upon your dev articles and I would like to contribute to this

**Comment by Balastrong** [comment]
Hey @AnoopFranc, thanks for sharing your interest in the project!

The goal of this issue is, as the title says, to prevent duplicates when picking many items all at once.

You might consider adding a new function to the `RandomPicker` class, I would suggest `pickManyDistinct` but you can come up with other names if you wish.
https://github.com/Balastrong/wrand/blob/cadc428d140ce3e5a12efc66c2deb7f6b2bf0bcb/src/randomPicker.ts#L3

This new function will act similarly as `pickMany` but will never return duplicates.

Feel free to give it a try and open a PR, I'll be happy to review it :)
